### ISSUE TITLE
Why not replace it?

### ISSUE THREAD

**Issue by bruno-melo** [PureDarwin/XPC#8]
Hi Cliff,

I was thinking about why PureDarwin as a separate project from Apple's macOS cannot replace closed macOS technologies to open alternatives like OpenRC? The last open launchd is from 2011/12, it's kind 5 years old and unmantained. Am I wrong or smells weird to see it being used nowadays?

**Comment by wjk** [comment]
I'm afraid that Apple's launchd _must_ be used with PureDarwin. Launchd is used for far more than just the boot process; it is the only native way to load a system daemon written for Darwin/macOS. (Other daemon-management tools must run on top of launchd, rendering them somewhat pointless.) Furthermore, the XPC subsystem is, technically speaking, a part of launchd, and more and more parts of the operating system (and the apps that run on it) reference XPC directly.

However, that being said, the version of launchd in this repository is _not_ the same as Apple's launchd package from 2011/12. It has been extended to support the libxpc API (which was never released by Apple in any form), and I have intended to rewrite other parts of the API (namely, launchctl) to be more in-line with the behavior of modern versions of macOS. However, real life often gets in the way, and I have not had very time to devote to this task.
